Task is to predict whether a bank currency note is authentic or not based on four attributes i.e.,variance of the image,wavelet transformed image,entropy and curtosis of image.

In [2]:
import pandas as pd,numpy as np
dataset = pd.read_csv("bank_authentication.csv")
dataset.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [3]:
dataset.isnull().sum()

Variance    0
Skewness    0
Curtosis    0
Entropy     0
Class       0
dtype: int64

In [8]:
#Prepare the dataset for training
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [12]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
#Training the algorithm
from sklearn.ensemble import RandomForestClassifier
cl = RandomForestClassifier(n_estimators = 30,random_state=1)
cl.fit(X_train,y_train)
y_predict=cl.predict(X_test)
#n_estimators:integer optional (default-100)-->the number of trees in the forest

In [16]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))
print(accuracy_score(y_test,y_predict)*100)

[[147  10]
 [ 33  85]]
              precision    recall  f1-score   support

           0       0.82      0.94      0.87       157
           1       0.89      0.72      0.80       118

    accuracy                           0.84       275
   macro avg       0.86      0.83      0.84       275
weighted avg       0.85      0.84      0.84       275

84.36363636363636


In [20]:
from sklearn.externals.six import StringIO
from sklearn.tree import export_graphviz
from pydotplus import graph_from_dot_data
from IPython.display import Image
import os
import os
os.environ["PATH"]+=os.pathsep +';'+r'C:\\ProgramData\\Anaconda3\\pkgs\\graphviz2.38\\bin'
dot_data = StringIO()
export_graphviz(cl.estimators_[1],out_file=dot_data,filled =True,
               rounded=True,class_names=['0','1'])
graph=graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())
graph.write_png("RTree.png")

True

In [21]:
cl.predict([[3.62160,8.6661,-2.8073,-0.44699]])

array([0], dtype=int64)

In [22]:
dataset = pd.read_csv("petrol_consumption.csv")

In [23]:
dataset.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [24]:
dataset.isnull().sum()

Petrol_tax                      0
Average_income                  0
Paved_Highways                  0
Population_Driver_licence(%)    0
Petrol_Consumption              0
dtype: int64

In [25]:
#Prepare the dataset for training
X = dataset.iloc[:,0:4].values
y=dataset.iloc[:,4].values

In [26]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [27]:
#FeatureScaling
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [28]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=20,random_state=0)
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

In [29]:
from sklearn import metrics
print("Mean Absolute Error:",metrics.mean_absolute_error(y_test,y_pred))
print("Mean Squared Error:",metrics.mean_squared_error(y_test,y_pred))
print("Root Mean Squared Error:",np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

Mean Absolute Error: 36.10499999999998
Mean Squared Error: 1748.3387499999997
Root Mean Squared Error: 41.81314087700181


In [36]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=150,random_state=0)
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

In [37]:
from sklearn import metrics
print("Mean Absolute Error:",metrics.mean_absolute_error(y_test,y_pred))
print("Mean Squared Error:",metrics.mean_squared_error(y_test,y_pred))
print("Root Mean Squared Error:",np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

Mean Absolute Error: 26.676666666666677
Mean Squared Error: 1332.2724044444456
Root Mean Squared Error: 36.50030690890757


In [38]:
y_pred = regressor.predict([[7.5,4870,2351,0.529]])
y_pred

array([496.07333333])